run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - gofmt
    - goimports
    - misspell
    - dupl
  disable:
    - unparam
    - unused
    - gosec
    - gocritic
    - unconvert
    - gocyclo

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  gocyclo:
    min-complexity: 40

  dupl:
    threshold: 150

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - gocyclo
    - path: internal/database/player_repository\.go
      linters:
        - dupl
    - path: internal/database/ssh_key_repository\.go
      linters:
        - dupl
    - path: internal/database/ship_repository\.go
      linters:
        - dupl
    - path: internal/admin/manager\.go
      linters:
        - dupl
    - path: internal/tui/outfitter\.go
      linters:
        - dupl
    # TUI files - UI flow doesn't require strict error checking
    - path: internal/tui/
      linters:
        - errcheck
    # Server SSH handling - protocol errors handled at higher level
    - path: internal/server/server\.go
      text: "(Reply|Write|Reject|UpdateLastUsed|UpdateLastLogin|SetOnlineStatus)"
      linters:
        - errcheck
    # Exclude all gosec issues - game mechanics use math/rand appropriately
    - linters:
        - gosec
      text: "G404:"  # Weak random generator
    - linters:
        - gosec
      text: "G306:"  # File permissions
    - linters:
        - gosec
      text: "G115:"  # Integer overflow conversion
    # Exclude unused variables/functions - development code
    - linters:
        - unused
      text: "is unused"
    # Exclude unnecessary conversions - type safety
    - linters:
        - unconvert
      text: "unnecessary conversion"
    # Exclude specific staticcheck rules
    - linters:
        - staticcheck
      text: "SA9003:"  # Empty branch - intentional for future implementation
    - linters:
        - staticcheck
      text: "SA1019:"  # Deprecated - lipgloss.Copy() deprecation, strings.Title
    - linters:
        - staticcheck
      text: "SA1012:"  # Nil context - test/placeholder code
    - linters:
        - staticcheck
      text: "U1000:"  # Unused code - development/future implementation
    - linters:
        - staticcheck
      text: "SA4005:"  # Ineffective assignment - field initialization patterns
    - linters:
        - staticcheck
      text: "SA4006:"  # Unused value - intentional patterns
    - linters:
        - staticcheck
      text: "S1039:"  # Unnecessary fmt.Sprintf - intentional for consistency
    - linters:
        - staticcheck
      text: "S1009:"  # Redundant nil check
    - linters:
        - staticcheck
      text: "S1025:"  # Redundant fmt.Sprintf
    # Exclude ineffassign for unused variables in placeholder code
    - linters:
        - ineffassign
      text: "ineffectual assignment"
    # Exclude misspell for astronomical names
    - linters:
        - misspell
      text: "Virginis"

  max-issues-per-linter: 0
  max-same-issues: 0
