run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gosec
    - gocritic
    - gocyclo
    - dupl
  disable:
    - unparam

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    enable-all: true
    disable:
      - shadow

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 150

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - gocyclo
    - path: internal/database/player_repository\.go
      linters:
        - dupl
    - path: internal/database/ssh_key_repository\.go
      linters:
        - dupl
    - path: internal/database/ship_repository\.go
      linters:
        - dupl
    - path: internal/admin/manager\.go
      linters:
        - dupl
    - path: internal/tui/outfitter\.go
      linters:
        - dupl
    # Exclude specific staticcheck rules
    - linters:
        - staticcheck
      text: "SA9003:"  # Empty branch - intentional for future implementation
    - linters:
        - staticcheck
      text: "SA1019:"  # Deprecated - lipgloss.Copy() deprecation
    - linters:
        - staticcheck
      text: "SA1012:"  # Nil context - test/placeholder code
    # Exclude ineffassign for unused variables in placeholder code
    - linters:
        - ineffassign
      text: "ineffectual assignment"
    # Exclude misspell for astronomical names
    - linters:
        - misspell
      text: "Virginis"

  max-issues-per-linter: 0
  max-same-issues: 0
