run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec
    - gocritic
    - gocyclo
    - dupl

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    enable-all: true

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 150

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - gocyclo
    - path: internal/database/player_repository\.go
      linters:
        - dupl
    - path: internal/database/ssh_key_repository\.go
      linters:
        - dupl
    - path: internal/database/ship_repository\.go
      linters:
        - dupl
    - path: internal/admin/manager\.go
      linters:
        - dupl
    - path: internal/tui/outfitter\.go
      linters:
        - dupl

  max-issues-per-linter: 0
  max-same-issues: 0
